version: '3'
services:
  db:
    image: postgres
    volumes:
      - $PWD/tmp/db:/var/lib/postgresql/data
  web:
    build: $PWD
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - $PWD:/todo-api
    ports:
      - "3000:3000"
    depends_on:
      - db
